import { auth } from "@clerk/nextjs/server"
import { after } from "next/server"
import {
  SYSTEM_PROMPT_DEFAULT,
  MCP_CONNECTION_TIMEOUT_MS,
  MCP_MAX_STEP_COUNT,
} from "@/lib/config"
import { getAllModels } from "@/lib/models"
import { getProviderForModel } from "@/lib/openproviders/provider-map"
import type { SupportedModel } from "@/lib/openproviders/types"
import {
  captureGeneration,
  flushPostHog,
  getPostHogClient,
} from "@/lib/posthog"
import type { Provider } from "@/lib/user-keys"
import { UIMessage as MessageAISDK, streamText, ToolSet, stepCountIs, convertToModelMessages } from "ai";
import type { ProviderOptions } from "@ai-sdk/provider-utils"
import { fetchMutation } from "convex/nextjs"
import { api } from "@/convex/_generated/api"
import type { Id } from "@/convex/_generated/dataModel"
import {
  checkServerSideUsage,
  incrementServerSideUsage,
  validateAndTrackUsage,
} from "./api"
import { createErrorResponse, extractErrorMessage } from "./utils"
import {
  loadUserMcpTools,
  type LoadToolsResult,
} from "@/lib/mcp/load-tools"

export const maxDuration = 60

type ChatRequest = {
  messages: MessageAISDK[]
  chatId: string
  model: string
  systemPrompt: string
  enableSearch: boolean
  message_group_id?: string
  userId?: string // Client-provided userId (for anonymous users)
}

export async function POST(req: Request) {
  // MCP state — declared outside try for cleanup in both after() and catch
  let mcpClients: LoadToolsResult["clients"] = []
  let mcpToolServerMap: LoadToolsResult["toolServerMap"] = new Map()

  try {
    // Server-side authentication - derive userId from Clerk session
    const { userId: authUserId, getToken } = await auth()
    const isAuthenticated = !!authUserId

    // Get Convex token for authenticated usage tracking
    const convexToken = isAuthenticated
      ? (await getToken({ template: "convex" })) ?? undefined
      : undefined

    const {
      messages,
      chatId,
      model,
      systemPrompt,
      enableSearch,
      message_group_id,
      userId: clientUserId,
    } = (await req.json()) as ChatRequest

    if (!messages || !chatId || !model) {
      return new Response(
        JSON.stringify({
          error: "Missing required fields",
          code: "INVALID_REQUEST",
          details: {
            messages: !messages ? "required" : "ok",
            chatId: !chatId ? "required" : "ok",
            model: !model ? "required" : "ok",
          },
        }),
        { status: 400 }
      )
    }

    // For anonymous users, require a guest ID for usage tracking
    // The client must provide a stable guest ID (format: "guest_<uuid>") from localStorage
    // This is generated by getOrCreateGuestUserId() on the client
    if (!isAuthenticated && !clientUserId) {
      return new Response(
        JSON.stringify({
          error: "Guest ID required for anonymous users",
          code: "MISSING_GUEST_ID",
        }),
        { status: 400 }
      )
    }

    // Use authenticated userId, or client-provided ID for anonymous users
    // At this point: if authenticated, authUserId is defined; if not, clientUserId is defined (validated above)
    const userId = authUserId ?? clientUserId!

    // For anonymous users, use clientUserId for rate limiting
    // This should match the format from getOrCreateGuestUserId: "guest_<uuid>"
    const anonymousId = !isAuthenticated ? clientUserId! : undefined

    // Server-side usage check - enforces rate limits before processing
    // For anonymous users, pass the anonymousId for tracking
    await checkServerSideUsage(convexToken, model, anonymousId)

    await validateAndTrackUsage({
      userId,
      model,
      isAuthenticated,
      token: convexToken,
    })

    // Increment usage count server-side with Convex
    await incrementServerSideUsage(convexToken, model, anonymousId)

    const allModels = await getAllModels()
    const modelConfig = allModels.find((m) => m.id === model)

    if (!modelConfig || !modelConfig.apiSdk) {
      throw new Error(`Model ${model} not found`)
    }

    const effectiveSystemPrompt = systemPrompt || SYSTEM_PROMPT_DEFAULT

    const provider = getProviderForModel(model as SupportedModel)

    let apiKey: string | undefined
    if (isAuthenticated && convexToken) {
      const { getEffectiveApiKey } = await import("@/lib/user-keys")
      apiKey =
        (await getEffectiveApiKey(
          provider as Provider,
          convexToken
        )) || undefined
    }

    // Pre-flight check: verify an API key is available before calling the provider.
    // When apiKey is undefined, the AI SDK falls back to environment variables.
    // If neither source has a valid key, the provider will reject with a 401.
    if (!apiKey) {
      const { env: providerEnv } = await import("@/lib/openproviders/env")
      const envKeyMap: Record<string, string | undefined> = {
        openai: providerEnv.OPENAI_API_KEY,
        mistral: providerEnv.MISTRAL_API_KEY,
        perplexity: providerEnv.PERPLEXITY_API_KEY,
        google: providerEnv.GOOGLE_GENERATIVE_AI_API_KEY,
        anthropic: providerEnv.ANTHROPIC_API_KEY,
        xai: providerEnv.XAI_API_KEY,
        openrouter: providerEnv.OPENROUTER_API_KEY,
      }
      const envKey = envKeyMap[provider]
      if (!envKey) {
        const providerName = modelConfig.provider || provider
        throw Object.assign(
          new Error(
            `No API key configured for ${providerName}. Please add your ${providerName} API key in settings.`
          ),
          { statusCode: 401, code: "MISSING_API_KEY" }
        )
      }
    }

    // Create base model from config
    const aiModel = modelConfig.apiSdk(apiKey, { enableSearch })

    // -----------------------------------------------------------------------
    // MCP Tool Loading
    // Gate on: auth + Convex token + feature flag + model capability
    // -----------------------------------------------------------------------
    let mcpTools: ToolSet = {} as ToolSet

    if (
      isAuthenticated &&
      convexToken &&
      process.env.ENABLE_MCP === "true" &&
      modelConfig.tools !== false
    ) {
      const mcpLoadStart = Date.now()
      const mcpResult = await loadUserMcpTools(convexToken, {
        timeout: MCP_CONNECTION_TIMEOUT_MS,
      })
      mcpTools = mcpResult.tools as ToolSet
      mcpClients = mcpResult.clients
      mcpToolServerMap = mcpResult.toolServerMap

      // PostHog: MCP tool loading observability
      const phClientForMcp = getPostHogClient()
      if (phClientForMcp) {
        phClientForMcp.capture({
          distinctId: userId,
          event: "mcp_tool_load",
          properties: {
            serverCount: mcpResult.clients.length,
            toolCount: Object.keys(mcpResult.tools).length,
            failedServers: mcpResult.failedServerCount,
            loadTimeMs: Date.now() - mcpLoadStart,
          },
        })
      }

      // Register MCP cleanup immediately after loading — before any code that
      // could throw.  after() runs even when the response errors or the client
      // disconnects, so this covers both the happy path and streaming failures.
      after(async () => {
        await Promise.allSettled(mcpClients.map((c) => c.close()))
      })
    }

    const hasMcpTools = Object.keys(mcpTools).length > 0
    const maxSteps = hasMcpTools ? MCP_MAX_STEP_COUNT : 10

    // Check if PostHog is configured for LLM analytics
    const phClient = getPostHogClient()
    const startTime = Date.now()

    // Schedule PostHog flush after streaming response completes
    // This ensures $ai_generation events are flushed before the serverless function terminates
    // Using flush() instead of shutdown() allows client reuse in warm containers
    if (phClient) {
      after(async () => {
        await flushPostHog()
      })
    }

    // Strip reasoning parts from message history before converting — but only
    // for non-Anthropic providers.  The OpenAI responses API rejects orphaned
    // reasoning items ("Item 'rs_...' of type 'reasoning' was provided without
    // its required following item").  Anthropic has the opposite requirement:
    // messages that were originally produced with extended thinking MUST be sent
    // back with their reasoning items ("Item 'msg_...' of type 'message' was
    // provided without its required 'reasoning' item").
    const shouldStripReasoning = provider !== "anthropic"

    const sanitizedMessages = shouldStripReasoning
      ? messages.map((msg) => {
          if (msg.role !== "assistant" || !msg.parts) return msg
          const hasReasoning = msg.parts.some(
            (part: { type: string }) => part.type === "reasoning"
          )
          if (!hasReasoning) return msg
          const filteredParts = msg.parts.filter(
            (part: { type: string }) => part.type !== "reasoning"
          )
          return {
            ...msg,
            parts: filteredParts.length > 0
              ? filteredParts
              : [{ type: "text" as const, text: "" }],
          }
        })
      : messages

    // Convert UIMessage[] to ModelMessage[] for streamText (v6)
    const modelMessages = await convertToModelMessages(sanitizedMessages)

    // Build provider-specific options to enable reasoning/thinking when
    // the selected model advertises support (reasoningText: true).
    const providerOptions: ProviderOptions = {}

    if (modelConfig.reasoningText) {
      if (provider === "anthropic") {
        let budgetTokens = 10000 // default
        if (model.includes("opus")) budgetTokens = 16000
        else if (model.includes("haiku")) budgetTokens = 5000
        else if (model.includes("sonnet")) budgetTokens = 12000

        providerOptions.anthropic = {
          thinking: { type: "enabled", budgetTokens },
        }
      } else if (provider === "google") {
        providerOptions.google = {
          thinkingConfig: { includeThoughts: true },
        }
      } else if (provider === "openai") {
        providerOptions.openai = {
          reasoningEffort: "medium",
        }
      } else if (provider === "xai") {
        providerOptions.xai = {
          reasoningEffort: "medium",
        }
      }
    }

    const result = streamText({
      model: aiModel,
      system: effectiveSystemPrompt,
      messages: modelMessages,
      tools: mcpTools,
      stopWhen: stepCountIs(maxSteps),
      ...(Object.keys(providerOptions).length > 0 && { providerOptions }),

      onError: (err: unknown) => {
        console.error("Streaming error occurred:", err)

        // Capture failed generations to PostHog for complete analytics
        if (phClient) {
          try {
            const latencyMs = Date.now() - startTime
            const errorMessage =
              err instanceof Error ? err.message : String(err)
            captureGeneration({
              distinctId: userId,
              traceId: chatId,
              model,
              provider,
              input: messages,
              output: null,
              latencyMs,
              isError: true,
              errorMessage,
              properties: {
                isAuthenticated,
                messageGroupId: message_group_id,
              },
            })
          } catch (captureErr) {
            console.error("[PostHog] Failed to capture error event:", captureErr)
          }
        }
      },

      onFinish: ({ text, usage, steps }) => {
        // Manually capture LLM generation for PostHog analytics
        // This ensures accurate output capture (withTracing has issues with streaming)
        if (phClient) {
          try {
            const latencyMs = Date.now() - startTime
            captureGeneration({
              distinctId: userId,
              traceId: chatId,
              model,
              provider,
              input: messages,
              output: text,
              inputTokens: usage?.inputTokens,
              outputTokens: usage?.outputTokens,
              latencyMs,
              properties: {
                isAuthenticated,
                messageGroupId: message_group_id,
              },
            })

            // PostHog: MCP tool call events — one event per tool invocation
            // Iterates through all steps to find tool calls that map to MCP tools.
            // durationMs per tool call requires wrapping tool.execute (future enhancement).
            if (steps && mcpToolServerMap.size > 0) {
              for (const step of steps) {
                if (step.toolCalls) {
                  for (const toolCall of step.toolCalls) {
                    const serverInfo = mcpToolServerMap.get(toolCall.toolName)
                    if (serverInfo) {
                      const toolResult = step.toolResults?.find(
                        (r: { toolCallId: string }) =>
                          r.toolCallId === toolCall.toolCallId
                      )
                      const success = toolResult
                        ? !(toolResult as { isError?: boolean }).isError
                        : false
                      phClient.capture({
                        distinctId: userId,
                        event: "mcp_tool_call",
                        properties: {
                          toolName: serverInfo.displayName,
                          serverName: serverInfo.serverName,
                          serverId: serverInfo.serverId,
                          namespacedToolName: toolCall.toolName,
                          success,
                          chatId,
                        },
                      })
                    }
                  }
                }
              }
            }
          } catch (captureErr) {
            // Analytics failure should never break the response
            console.error(
              "[PostHog] Failed to capture generation event:",
              captureErr
            )
          }
        }

        // Audit log: persist MCP tool calls to mcpToolCallLog (fire-and-forget).
        // These writes are best-effort — failures are swallowed to avoid breaking
        // the streaming response. Follows the same pattern as updateConnectionStatus
        // in lib/mcp/load-tools.ts.
        if (convexToken && steps && mcpToolServerMap.size > 0) {
          for (const step of steps) {
            if (step.toolCalls) {
              for (const toolCall of step.toolCalls) {
                const serverInfo = mcpToolServerMap.get(toolCall.toolName)
                if (!serverInfo) continue

                // Find matching tool result for output preview
                const toolResult = step.toolResults?.find(
                  (r: { toolCallId: string }) =>
                    r.toolCallId === toolCall.toolCallId
                )

                const success = toolResult
                  ? !(toolResult as { isError?: boolean }).isError
                  : false

                void fetchMutation(
                  api.mcpToolCallLog.log,
                  {
                    chatId: chatId as Id<"chats">,
                    serverId: serverInfo.serverId as Id<"mcpServers">,
                    toolName: serverInfo.displayName,
                    toolCallId: toolCall.toolCallId,
                    inputPreview: JSON.stringify(toolCall.input).slice(0, 500),
                    outputPreview: toolResult
                      ? JSON.stringify(toolResult.output).slice(0, 500)
                      : undefined,
                    success,
                  },
                  { token: convexToken }
                ).catch(() => {
                  // Intentionally swallowed — audit logging is best-effort
                })
              }
            }
          }
        }
      }
    })

    return result.toUIMessageStreamResponse({
      sendReasoning: true,
      sendSources: true,
      onError: (error: unknown) => {
        console.error("Error forwarded to client:", error)
        return extractErrorMessage(error)
      },
    });
  } catch (err: unknown) {
    // Clean up any MCP clients that were opened before the error
    await Promise.allSettled(mcpClients.map((c) => c.close()))

    console.error("Error in /api/chat:", err)
    const error = err as {
      code?: string
      message?: string
      statusCode?: number
    }

    return createErrorResponse(error)
  }
}
