import { auth } from "@clerk/nextjs/server"
import { after } from "next/server"
import {
  SYSTEM_PROMPT_DEFAULT,
  MCP_CONNECTION_TIMEOUT_MS,
  MCP_MAX_STEP_COUNT,
  DEFAULT_MAX_STEP_COUNT,
  ANONYMOUS_MAX_STEP_COUNT,
} from "@/lib/config"
import { getAllModels } from "@/lib/models"
import { getProviderForModel } from "@/lib/openproviders/provider-map"
import type { SupportedModel } from "@/lib/openproviders/types"
import {
  captureGeneration,
  flushPostHog,
  getPostHogClient,
} from "@/lib/posthog"
import type { Provider } from "@/lib/user-keys"
import { UIMessage as MessageAISDK, streamText, ToolSet, stepCountIs, convertToModelMessages } from "ai";
import type { ProviderOptions } from "@ai-sdk/provider-utils"
import { fetchMutation } from "convex/nextjs"
import { api } from "@/convex/_generated/api"
import type { Id } from "@/convex/_generated/dataModel"
import {
  checkServerSideUsage,
  incrementServerSideUsage,
  validateAndTrackUsage,
} from "./api"
import { createErrorResponse, extractErrorMessage } from "./utils"
import {
  loadUserMcpTools,
  type LoadToolsResult,
} from "@/lib/mcp/load-tools"

export const maxDuration = 60

type ChatRequest = {
  messages: MessageAISDK[]
  chatId: string
  model: string
  systemPrompt: string
  enableSearch: boolean
  message_group_id?: string
  userId?: string // Client-provided userId (for anonymous users)
}

export async function POST(req: Request) {
  // MCP state — declared outside try for cleanup in both after() and catch
  let mcpClients: LoadToolsResult["clients"] = []
  let mcpToolServerMap: LoadToolsResult["toolServerMap"] = new Map()

  try {
    // Server-side authentication - derive userId from Clerk session
    const { userId: authUserId, getToken } = await auth()
    const isAuthenticated = !!authUserId

    // Get Convex token for authenticated usage tracking
    const convexToken = isAuthenticated
      ? (await getToken({ template: "convex" })) ?? undefined
      : undefined

    const {
      messages,
      chatId,
      model,
      systemPrompt,
      enableSearch,
      message_group_id,
      userId: clientUserId,
    } = (await req.json()) as ChatRequest

    if (!messages || !chatId || !model) {
      return new Response(
        JSON.stringify({
          error: "Missing required fields",
          code: "INVALID_REQUEST",
          details: {
            messages: !messages ? "required" : "ok",
            chatId: !chatId ? "required" : "ok",
            model: !model ? "required" : "ok",
          },
        }),
        { status: 400 }
      )
    }

    // For anonymous users, require a guest ID for usage tracking
    // The client must provide a stable guest ID (format: "guest_<uuid>") from localStorage
    // This is generated by getOrCreateGuestUserId() on the client
    if (!isAuthenticated && !clientUserId) {
      return new Response(
        JSON.stringify({
          error: "Guest ID required for anonymous users",
          code: "MISSING_GUEST_ID",
        }),
        { status: 400 }
      )
    }

    // Use authenticated userId, or client-provided ID for anonymous users
    // At this point: if authenticated, authUserId is defined; if not, clientUserId is defined (validated above)
    const userId = authUserId ?? clientUserId!

    // For anonymous users, use clientUserId for rate limiting
    // This should match the format from getOrCreateGuestUserId: "guest_<uuid>"
    const anonymousId = !isAuthenticated ? clientUserId! : undefined

    // Server-side usage check - enforces rate limits before processing
    // For anonymous users, pass the anonymousId for tracking
    await checkServerSideUsage(convexToken, model, anonymousId)

    await validateAndTrackUsage({
      userId,
      model,
      isAuthenticated,
      token: convexToken,
    })

    // Increment usage count server-side with Convex
    await incrementServerSideUsage(convexToken, model, anonymousId)

    const allModels = await getAllModels()
    const modelConfig = allModels.find((m) => m.id === model)

    if (!modelConfig || !modelConfig.apiSdk) {
      throw new Error(`Model ${model} not found`)
    }

    const effectiveSystemPrompt = systemPrompt || SYSTEM_PROMPT_DEFAULT

    const provider = getProviderForModel(model as SupportedModel)

    let apiKey: string | undefined
    if (isAuthenticated && convexToken) {
      const { getEffectiveApiKey } = await import("@/lib/user-keys")
      apiKey =
        (await getEffectiveApiKey(
          provider as Provider,
          convexToken
        )) || undefined
    }

    // Pre-flight check: verify an API key is available before calling the provider.
    // When apiKey is undefined, the AI SDK falls back to environment variables.
    // If neither source has a valid key, the provider will reject with a 401.
    if (!apiKey) {
      const { env: providerEnv } = await import("@/lib/openproviders/env")
      const envKeyMap: Record<string, string | undefined> = {
        openai: providerEnv.OPENAI_API_KEY,
        mistral: providerEnv.MISTRAL_API_KEY,
        perplexity: providerEnv.PERPLEXITY_API_KEY,
        google: providerEnv.GOOGLE_GENERATIVE_AI_API_KEY,
        anthropic: providerEnv.ANTHROPIC_API_KEY,
        xai: providerEnv.XAI_API_KEY,
        openrouter: providerEnv.OPENROUTER_API_KEY,
      }
      const envKey = envKeyMap[provider]
      if (!envKey) {
        const providerName = modelConfig.provider || provider
        throw Object.assign(
          new Error(
            `No API key configured for ${providerName}. Please add your ${providerName} API key in settings.`
          ),
          { statusCode: 401, code: "MISSING_API_KEY" }
        )
      }
    }

    // enableSearch is no longer passed to the model — it controls tool injection below.
    // All search is now provided via visible, auditable tool calls (Layer 1 or Layer 2).
    const aiModel = modelConfig.apiSdk(apiKey)

    // -----------------------------------------------------------------------
    // Search Tool Loading (Layer 1 — Built-in Provider Tools)
    //
    // The `enableSearch` flag from the client is the MASTER SWITCH for search
    // tool injection. When true, route.ts injects search tools:
    //   - If the provider has native search tools → use them (Layer 1)
    //   - If not → use Exa fallback (Layer 2, added in Phase 3)
    //
    // This replaces the previous dual mechanism where `enableSearch` was
    // passed to `modelConfig.apiSdk()` as an opaque provider-level flag.
    // All search is now visible, auditable tool calls.
    //
    // NOT gated on isAuthenticated. Anonymous users (5 daily messages)
    // get search tools when the platform has provider API keys configured.
    // When apiKey is undefined (anonymous), the provider factory falls back
    // to the env var — same behavior as model creation above.
    // -----------------------------------------------------------------------
    let builtInTools: ToolSet = {} as ToolSet
    let builtInToolMetadata = new Map<string, import("@/lib/tools/types").ToolMetadata>()

    const shouldInjectSearch = enableSearch && modelConfig.tools !== false

    if (shouldInjectSearch) {
      const { getProviderTools } = await import("@/lib/tools/provider")
      const providerResult = await getProviderTools(provider, apiKey)
      builtInTools = providerResult.tools
      builtInToolMetadata = providerResult.metadata
    }

    // -----------------------------------------------------------------------
    // Third-Party Tool Loading (Layer 2)
    // Universal search fallback for providers without native search tools.
    // Only loaded when enableSearch is true AND Layer 1 didn't provide search.
    //
    // The coordination model is simple:
    //   - enableSearch === true: route.ts injects search tools
    //   - Layer 1 provided search (builtInHasSearch): skip Layer 2
    //   - Layer 1 did NOT provide search: load Layer 2 Exa fallback
    //
    // NOT gated on isAuthenticated — anonymous users get search when
    // the platform has an EXA_API_KEY configured (same as Layer 1).
    // -----------------------------------------------------------------------
    let thirdPartyTools: ToolSet = {} as ToolSet
    let thirdPartyToolMetadata = new Map<string, import("@/lib/tools/types").ToolMetadata>()

    if (shouldInjectSearch) {
      const builtInHasSearch = Object.keys(builtInTools).length > 0

      // Only load Layer 2 when Layer 1 didn't provide search.
      // This is the sole coordination point — third-party.ts does not
      // know about providers. It just receives a skipSearch flag.
      if (!builtInHasSearch) {
        const { getThirdPartyTools } = await import("@/lib/tools/third-party")

        // Key resolution: user BYOK key → platform env var → undefined
        // The exa-js SDK accepts keys in its constructor, so BYOK keys
        // are passed directly — no env var manipulation needed.
        let resolvedExaKey: string | undefined
        if (convexToken) {
          const { getEffectiveToolKey } = await import("@/lib/user-keys")
          resolvedExaKey = await getEffectiveToolKey("exa", convexToken)
        }
        if (!resolvedExaKey) {
          resolvedExaKey = process.env.EXA_API_KEY
        }

        const thirdPartyResult = await getThirdPartyTools({
          skipSearch: false, // We already know we need search (builtInHasSearch is false)
          exaKey: resolvedExaKey,
        })
        thirdPartyTools = thirdPartyResult.tools
        thirdPartyToolMetadata = thirdPartyResult.metadata
      }
    }

    // -----------------------------------------------------------------------
    // MCP Tool Loading
    // Gate on: auth + Convex token + model capability
    // -----------------------------------------------------------------------
    let mcpTools: ToolSet = {} as ToolSet

    if (
      isAuthenticated &&
      convexToken &&
      modelConfig.tools !== false
    ) {
      const mcpLoadStart = Date.now()
      const mcpResult = await loadUserMcpTools(convexToken, {
        timeout: MCP_CONNECTION_TIMEOUT_MS,
      })
      mcpTools = mcpResult.tools as ToolSet
      mcpClients = mcpResult.clients
      mcpToolServerMap = mcpResult.toolServerMap

      // PostHog: MCP tool loading observability
      const phClientForMcp = getPostHogClient()
      if (phClientForMcp) {
        phClientForMcp.capture({
          distinctId: userId,
          event: "mcp_tool_load",
          properties: {
            serverCount: mcpResult.clients.length,
            toolCount: Object.keys(mcpResult.tools).length,
            failedServers: mcpResult.failedServerCount,
            loadTimeMs: Date.now() - mcpLoadStart,
          },
        })
      }

      // Register MCP cleanup immediately after loading — before any code that
      // could throw.  after() runs even when the response errors or the client
      // disconnects, so this covers both the happy path and streaming failures.
      after(async () => {
        await Promise.allSettled(mcpClients.map((c) => c.close()))
      })
    }

    // Merge all tool layers: search (Layer 1 OR Layer 2) + MCP (Layer 3)
    // Search tools are mutually exclusive: Layer 1 XOR Layer 2 (never both).
    // MCP tools are always independent and additive.
    // Spread order matters for conflict resolution:
    //   1. Built-in/third-party search tools (lowest priority)
    //   2. MCP tools (highest priority — user-configured, namespaced)
    const searchTools = { ...builtInTools, ...thirdPartyTools }
    const allTools = { ...searchTools, ...mcpTools } as ToolSet

    // Dev-mode collision detection: warn when duplicate keys are found
    if (process.env.NODE_ENV !== "production") {
      const searchKeys = new Set(Object.keys(searchTools))
      for (const key of Object.keys(mcpTools)) {
        if (searchKeys.has(key)) {
          console.warn(`[tools] Key collision: "${key}" exists in both search and MCP tools. MCP wins.`)
        }
      }
    }

    const hasAnyTools = Object.keys(allTools).length > 0

    // Anonymous users get a lower step count to limit tool call cost exposure.
    // Authenticated users get the full MCP_MAX_STEP_COUNT (20).
    const maxSteps = hasAnyTools
      ? (isAuthenticated ? MCP_MAX_STEP_COUNT : ANONYMOUS_MAX_STEP_COUNT)
      : DEFAULT_MAX_STEP_COUNT

    // Check if PostHog is configured for LLM analytics
    const phClient = getPostHogClient()
    const startTime = Date.now()

    // Schedule PostHog flush after streaming response completes
    // This ensures $ai_generation events are flushed before the serverless function terminates
    // Using flush() instead of shutdown() allows client reuse in warm containers
    if (phClient) {
      after(async () => {
        await flushPostHog()
      })
    }

    // Strip reasoning parts from message history before converting — but only
    // for non-Anthropic providers.  The OpenAI responses API rejects orphaned
    // reasoning items ("Item 'rs_...' of type 'reasoning' was provided without
    // its required following item").  Anthropic has the opposite requirement:
    // messages that were originally produced with extended thinking MUST be sent
    // back with their reasoning items ("Item 'msg_...' of type 'message' was
    // provided without its required 'reasoning' item").
    const shouldStripReasoning = provider !== "anthropic"

    const sanitizedMessages = shouldStripReasoning
      ? messages.map((msg) => {
          if (msg.role !== "assistant" || !msg.parts) return msg
          const hasReasoning = msg.parts.some(
            (part: { type: string }) => part.type === "reasoning"
          )
          if (!hasReasoning) return msg
          const filteredParts = msg.parts.filter(
            (part: { type: string }) => part.type !== "reasoning"
          )
          return {
            ...msg,
            parts: filteredParts.length > 0
              ? filteredParts
              : [{ type: "text" as const, text: "" }],
          }
        })
      : messages

    // Convert UIMessage[] to ModelMessage[] for streamText (v6)
    const modelMessages = await convertToModelMessages(sanitizedMessages)

    // Build provider-specific options to enable reasoning/thinking when
    // the selected model advertises support (reasoningText: true).
    //
    // Anthropic thinking configuration is context-aware:
    //   - Models with thinkingMode: "adaptive" (Opus 4.6+) use Anthropic's
    //     adaptive allocation — the recommended mode per Anthropic's docs.
    //     "enabled" with budget_tokens is deprecated on Opus 4.6.
    //   - Older models use "enabled" with a fixed budgetTokens.
    //
    // IMPORTANT: Server-side web search results (encrypted_content) are
    // counted as INPUT tokens, not output tokens. They do NOT consume from
    // the max_tokens budget. (Source: Anthropic web search tool docs)
    //
    // SDK LIMITATION (ai@6.0.78 / @ai-sdk/anthropic@3.0.41):
    // When adaptive thinking is used with server-side tools (web search),
    // the Anthropic API may return stop_reason: "pause_turn" — indicating
    // the model needs a follow-up request to continue generating text. The
    // AI SDK maps "pause_turn" to the same unified finishReason as "end_turn"
    // ("stop") and the step continuation logic does not re-send the
    // conversation. This results in responses with reasoning + tool results
    // but zero text content.
    //
    // WORKAROUND: When search tools are active, fall back to "enabled"
    // thinking with a conservative budget. This produces a complete response
    // in a single API call (no pause_turn). For non-search requests,
    // adaptive thinking works correctly and is preferred.
    const providerOptions: ProviderOptions = {}

    if (modelConfig.reasoningText) {
      if (provider === "anthropic") {
        if (modelConfig.thinkingMode === "adaptive") {
          if (shouldInjectSearch) {
            // Adaptive + server-side web search triggers pause_turn in the
            // Anthropic API, which the AI SDK does not handle (see above).
            // Fall back to "enabled" with a budget that leaves ample room
            // for text output. Search results are input tokens, so they
            // don't consume from max_tokens — no reduction needed.
            providerOptions.anthropic = {
              thinking: { type: "enabled", budgetTokens: 10000 },
            }
          } else {
            // Opus 4.6+ without search — use adaptive thinking as recommended.
            // The model dynamically allocates between thinking and text, with
            // interleaved thinking automatically enabled for tool use.
            providerOptions.anthropic = {
              thinking: { type: "adaptive" },
            }
          }
        } else {
          // Older models — fixed budget.
          let budgetTokens = 10000 // default
          if (model.includes("opus")) budgetTokens = 16000
          else if (model.includes("haiku")) budgetTokens = 5000
          else if (model.includes("sonnet")) budgetTokens = 12000

          providerOptions.anthropic = {
            thinking: { type: "enabled", budgetTokens },
          }
        }
      } else if (provider === "google") {
        providerOptions.google = {
          thinkingConfig: { includeThoughts: true },
        }
      } else if (provider === "openai") {
        providerOptions.openai = {
          reasoningEffort: "medium",
        }
      } else if (provider === "xai") {
        providerOptions.xai = {
          reasoningEffort: "medium",
        }
      }
    }

    const result = streamText({
      model: aiModel,
      system: effectiveSystemPrompt,
      messages: modelMessages,
      tools: allTools,
      stopWhen: stepCountIs(maxSteps),
      ...(Object.keys(providerOptions).length > 0 && { providerOptions }),

      onError: (err: unknown) => {
        console.error("Streaming error occurred:", err)

        // Capture failed generations to PostHog for complete analytics
        if (phClient) {
          try {
            const latencyMs = Date.now() - startTime
            const errorMessage =
              err instanceof Error ? err.message : String(err)
            captureGeneration({
              distinctId: userId,
              traceId: chatId,
              model,
              provider,
              input: messages,
              output: null,
              latencyMs,
              isError: true,
              errorMessage,
              properties: {
                isAuthenticated,
                messageGroupId: message_group_id,
              },
            })
          } catch (captureErr) {
            console.error("[PostHog] Failed to capture error event:", captureErr)
          }
        }
      },

      onFinish: ({ text, usage, steps, finishReason }) => {
        // ---------------------------------------------------------------
        // Finish reason observability
        // Log when the response was truncated (finishReason: "length")
        // so we can detect max_tokens exhaustion in dev and production.
        // ---------------------------------------------------------------
        if (finishReason === "length") {
          console.warn(
            `[chat] Response truncated (finishReason: "length") — model: ${model}, ` +
            `outputTokens: ${usage?.outputTokens ?? "?"}, ` +
            `inputTokens: ${usage?.inputTokens ?? "?"}`
          )
        }
        if (process.env.NODE_ENV !== "production") {
          // Log both unified and raw finish reasons. The raw reason reveals
          // provider-specific signals (e.g. Anthropic's "pause_turn" vs
          // "end_turn") that the unified reason collapses into "stop".
          const rawReason = steps?.[steps.length - 1]?.rawFinishReason
          console.log(
            `[chat] finishReason: ${finishReason}` +
            `${rawReason && rawReason !== finishReason ? ` (raw: ${rawReason})` : ""}, ` +
            `model: ${model}, ` +
            `tokens: ${usage?.inputTokens ?? "?"}in/${usage?.outputTokens ?? "?"}out, ` +
            `text: ${text?.length ?? 0} chars`
          )
        }

        // Manually capture LLM generation for PostHog analytics
        // This ensures accurate output capture (withTracing has issues with streaming)
        if (phClient) {
          try {
            const latencyMs = Date.now() - startTime
            captureGeneration({
              distinctId: userId,
              traceId: chatId,
              model,
              provider,
              input: messages,
              output: text,
              inputTokens: usage?.inputTokens,
              outputTokens: usage?.outputTokens,
              latencyMs,
              properties: {
                isAuthenticated,
                messageGroupId: message_group_id,
                finishReason,
              },
            })

            // PostHog: unified tool call events — one event per tool invocation (all sources)
            // Replaces the previous MCP-only mcp_tool_call event.
            if (steps) {
              // Combine all metadata maps for source identification
              const allToolMetadata = new Map([...builtInToolMetadata, ...thirdPartyToolMetadata])

              for (const step of steps) {
                if (step.toolCalls) {
                  for (const toolCall of step.toolCalls) {
                    const mcpServerInfo = mcpToolServerMap.get(toolCall.toolName)
                    const nonMcpMeta = allToolMetadata.get(toolCall.toolName)

                    // Determine source and service name
                    const source = mcpServerInfo ? "mcp" : (nonMcpMeta?.source ?? "unknown")
                    const serviceName = mcpServerInfo
                      ? mcpServerInfo.serverName
                      : (nonMcpMeta?.serviceName ?? "unknown")
                    const displayName = mcpServerInfo
                      ? mcpServerInfo.displayName
                      : (nonMcpMeta?.displayName ?? toolCall.toolName)

                    const toolResult = step.toolResults?.find(
                      (r: { toolCallId: string }) => r.toolCallId === toolCall.toolCallId
                    )
                    const success = toolResult
                      ? !(toolResult as { isError?: boolean }).isError
                      : false

                    phClient.capture({
                      distinctId: userId,
                      event: "tool_call",
                      properties: {
                        toolName: displayName,
                        rawToolName: toolCall.toolName,
                        source,
                        serviceName,
                        success,
                        chatId,
                        // MCP-specific (optional)
                        ...(mcpServerInfo && {
                          serverId: mcpServerInfo.serverId,
                          serverName: mcpServerInfo.serverName,
                        }),
                      },
                    })
                  }
                }
              }
            }
          } catch (captureErr) {
            // Analytics failure should never break the response
            console.error(
              "[PostHog] Failed to capture generation event:",
              captureErr
            )
          }
        }

        // Audit log: persist MCP tool calls to toolCallLog (fire-and-forget).
        // These writes are best-effort — failures are swallowed to avoid breaking
        // the streaming response. Follows the same pattern as updateConnectionStatus
        // in lib/mcp/load-tools.ts.
        if (convexToken && steps && mcpToolServerMap.size > 0) {
          for (const step of steps) {
            if (step.toolCalls) {
              for (const toolCall of step.toolCalls) {
                const serverInfo = mcpToolServerMap.get(toolCall.toolName)
                if (!serverInfo) continue

                // Find matching tool result for output preview
                const toolResult = step.toolResults?.find(
                  (r: { toolCallId: string }) =>
                    r.toolCallId === toolCall.toolCallId
                )

                const success = toolResult
                  ? !(toolResult as { isError?: boolean }).isError
                  : false

                void fetchMutation(
                  api.toolCallLog.log,
                  {
                    chatId: chatId as Id<"chats">,
                    serverId: serverInfo.serverId as Id<"mcpServers">,
                    toolName: serverInfo.displayName,
                    toolCallId: toolCall.toolCallId,
                    inputPreview: JSON.stringify(toolCall.input).slice(0, 500),
                    outputPreview: toolResult
                      ? JSON.stringify(toolResult.output).slice(0, 500)
                      : undefined,
                    success,
                    source: "mcp",
                    serviceName: serverInfo.serverName,
                  },
                  { token: convexToken }
                ).catch(() => {
                  // Intentionally swallowed — audit logging is best-effort
                })
              }
            }
          }
        }

        // Audit log: persist built-in + third-party tool calls (fire-and-forget).
        // Identifies non-MCP tools by checking if the tool name is NOT in mcpToolServerMap.
        if (convexToken && steps) {
          // Combine built-in and third-party metadata maps
          const nonMcpMetadata = new Map([...builtInToolMetadata, ...thirdPartyToolMetadata])

          if (nonMcpMetadata.size > 0) {
            for (const step of steps) {
              if (step.toolCalls) {
                for (const toolCall of step.toolCalls) {
                  // Skip MCP tools (already logged above)
                  if (mcpToolServerMap.get(toolCall.toolName)) continue

                  const meta = nonMcpMetadata.get(toolCall.toolName)
                  if (!meta) continue // Unknown tool — skip

                  const toolResult = step.toolResults?.find(
                    (r: { toolCallId: string }) =>
                      r.toolCallId === toolCall.toolCallId
                  )
                  const success = toolResult
                    ? !(toolResult as { isError?: boolean }).isError
                    : false

                  void fetchMutation(
                    api.toolCallLog.log,
                    {
                      chatId: chatId as Id<"chats">,
                      // No serverId for non-MCP tools
                      toolName: meta.displayName,
                      toolCallId: toolCall.toolCallId,
                      inputPreview: JSON.stringify(toolCall.input).slice(0, 500),
                      outputPreview: toolResult
                        ? JSON.stringify(toolResult.output).slice(0, 500)
                        : undefined,
                      success,
                      source: meta.source,
                      serviceName: meta.serviceName,
                    },
                    { token: convexToken }
                  ).catch(() => {
                    // Intentionally swallowed — audit logging is best-effort
                  })
                }
              }
            }
          }
        }
      }
    })

    return result.toUIMessageStreamResponse({
      sendReasoning: true,
      sendSources: true,
      onError: (error: unknown) => {
        console.error("Error forwarded to client:", error)
        return extractErrorMessage(error)
      },
    });
  } catch (err: unknown) {
    // Clean up any MCP clients that were opened before the error
    await Promise.allSettled(mcpClients.map((c) => c.close()))

    console.error("Error in /api/chat:", err)
    const error = err as {
      code?: string
      message?: string
      statusCode?: number
    }

    return createErrorResponse(error)
  }
}
